version: "3"
services:

  laravel:
    image: hitalos/laravel
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - $PWD:/var/www
  mysql:
    image: mysql:5.7.22
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: angie
    volumes:
      - angie_data

volumes:
  angie_data: